language: cpp

compiler:
  - clang
  - gcc

# This method for installing apt-based dependencies works in
# container-based build (sudoless). Should use it if possible.
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8 # Get -std=c++11 support
      - g++-4.8

before_install:
  - sudo add-apt-repository ppa:amarburg/opencv3 --yes
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -y g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

install:
  - sudo apt-get install -y libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev libv4l-dev
  - sudo apt-get install -y libopencv3-dev

before_script:

  # Install boost
  - cd $TRAVIS_BUILD_DIR
  - wget https://sourceforge.net/projects/boost/files/boost/1.63.0/boost_1_63_0.tar.bz2/download -O tarboost
  - tar -xf tarboost
  - cd ./boost*
  - ./bootstrap.sh
  - ./b2 --with-program_options --with-system --with-thread --with-filesystem
  - cd ..
  - sudo mv boost* /opt

  # Get zeromq
  - cd $TRAVIS_BUILD_DIR
  - wget https://github.com/zeromq/zeromq4-1/releases/download/v4.1.4/zeromq-4.1.4.tar.gz -O tarzmq
  - tar -xf tarzmq
  - cd ./zeromq*
  - ./configure --without-libsodium
  - make 
  - sudo make install
  - sudo ldconfig 

  # Get zeromq cpp bindings
  - cd $TRAVIS_BUILD_DIR
  - wget https://raw.githubusercontent.com/zeromq/cppzmq/master/zmq.hpp
  - sudo mv zmq.hpp /usr/local/include/

  # Configure build
  # Debug build includes throw expressions required to pass tests but optimized
  # out of release build. I don't use asserts because they dont allow shmem
  # cleanup.
  - cd $TRAVIS_BUILD_DIR
  - mkdir debug 
  - cd debug
  - boost_dir=`ls /opt/ | grep boost`
  - cmake -DCMAKE_BUILD_TYPE=Debug -DBOOST_ROOT=/opt/$boost_dir ..

script: make && make test
